### PR TITLE
feat: add tabs for swift and kotlin to the starter (quickstart) example

### PR DESCRIPTION
**Pull request by riverKanies**
most of the heavy lifting to merge starter.md and basics.md

todo:
- rename 'starter.md' to 'quickstart'
- actually test run swift and kotlin code (and make any necessary changes to those examples)

**Edited**, todos previously included:
- move mnemonic and descriptor creation logic from basics.md to new 'full wallet' example
- delete basics.md
but I added a commit with these changes. note, I don't want to rename the 'starter' to 'quickstart' in this PR as that would make the diff harder to parse

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Looking good, thanks for merging the two pages!

I would keep the Kotlin and Swift code hard-coded in the pages until we actually have running examples we can trigger in the CI.

Some further context on extra languages: I like having the 3 languages on the starter/quickstart page, because (a) it reinforces that we provide language bindings, and (b) it gives a teaser to what could be done for all pages if we really went there. But in the short term, I don't want to put energy in writing/testing code for the other languages. The book is there to show how to use the libraries, and a decent amount of what you can do in Rust you should be able to do in the other languages (but not all! and in some cases the API is changed/simplified). Until we have a full book we're happy with in Rust, I think the focus should be on writing the meat/content. Once we have that, we can pick some/all pages and write their language counterparts (note also that in theory there is also Python + React Native (JS) + Flutter (Dart). This does not impact this page directly, but I just thought I'd let you know before you go too deep the Swift/Android/Python rabbit holes!

**Comment by riverKanies** [comment]
ok, definitely good to know that I shouldn't be putting much energy into languages other than rust

however, the OCD part of me would really prefer to have code in code files that is pulled in as snippets even if the code isn't 100% runnable and tested. If we just add some comments to the code files indicating that they are WIP I think that could be ok don't you?
also moving them back into the .md file is more effort that's taking away from adding content... and we will eventually want them in code files @thunderbiscuit

**Comment by thunderbiscuit** [comment]
I see your point about wanting them all in one place, but way weirder for Kotlin and Swift devs is to have odd floating files that are not compatible with anything, not part of an actual project an IDE can load, and cannot be compiled as is; they're just code blocks that are then loaded somewhere else. It's a bit similar to how you wanted Rust to work in VSCode IMO.

No sweat about the extra work I can do it later.

**Comment by thunderbiscuit** [comment]
One other question actually: what is the purpose of the rust/full-wallet example? I can see it's been added but I can't find a link to it in the docs.

**Comment by riverKanies** [comment]
well it's just that these are open questions for me. It's not obvious to me that i couldn't get the swift and kotlin examples working with some pretty minor effort and that was my plan. I know it's possible to just run a swift file at the terminal. 

and with the rust workspace it was the same deal. I thought we might actually want to enforce version consistency, but we don't.

I guess more generally I just feel that this PR is a step in the right direction and we should just merge and cross those bridges when we come to them. to me, leaving code in the .md assumes we won't get examples for other languages before the book releases, which I assumed we would have at least for the quickstart and full-wallet, in which case putting snippets in code files, even if not yet runnable, is still a step in the right direction

**Comment by riverKanies** [comment]
in the second commit i marked that as WIP. this was so that i could delete the basics.md file without losing any code, because some of the code from basics will be in full-wallet but not quickstart.

This is what I mean by just iterating towards the goal, we're not doing continuous deployment yet, the book isn't really in live use it's very much wip, so I'm optimizing for time to first release right now. Also I've been making notes of the todos on my PRs

**Comment by thunderbiscuit** [comment]
Yes indeed you can run all 3 languages as scripting languages directly from your command line (which is super sweet). Check out [this repo](https://github.com/thunderbiscuit/bitcoindevkit-scripts) where we do just that (I think we have just over 30 scripts/examples). Feel free to contribute to this too if you're ever so inclined!

They do however require a bit of massaging to make work that way (Rust and Kotlin the most), and few devs are super familiar with them.

Anyway yep sorry I missed your todo on testing the Kotlin/Swift code. I'd say: don't spend too much time on those if you haven't run those stacks before (or do it! it's fun to learn of course).

**Comment by thunderbiscuit** [comment]
Sorry I re-read my comment above and I might not have been clear:
> It's a bit similar to how you wanted Rust to work in VSCode IMO.

By this I meant that it felt important that your IDE was able to read and understand the Rust code, including the ability to click into types and everything else. That's what I mean for the Kotlin and Swift devs. It'd be great to provide that for them too, and hence a full example with gradle build scripts and Xcode config files will be required. But this is not required here, and I figured it'd be easier to keep the non-compiling Kotlin code in the markdown files until someone can PR the full compilable examples, but the snippets work too.

**Comment by riverKanies** [comment]
ah ok, that makes more sense now

the other reason to use snippets on the quickstart is because we print the full file, so it would be duplicated if it's inline. this i see as the lowest effort approach, but I do recognize there is work to do on the other language examples to get where we want, either make them runnable, or note that they aren't

**Comment by riverKanies** [comment]
in response to:
> Yes indeed you can run all 3 languages as scripting languages directly from your command line (which is super sweet). Check out [this repo](https://github.com/thunderbiscuit/bitcoindevkit-scripts) where we do just that (I think we have just over 30 scripts/examples). Feel free to contribute to this too if you're ever so inclined!
> 
> They do however require a bit of massaging to make work that way (Rust and Kotlin the most), and few devs are super familiar with them.
Ah, ok, I suspected that might be the case, and I recognize that the current starter instructions assume the reader is acutally building an app in xcode or android studio, so I fully expected some modifications to the code and instructions would probably be warranted. 
Give me a day or so to play around with it and see how it feels. If it's not too much of a lift, I'd like to be able to do the quickstart and full-wallet examples in all languages. That may require having a scripting implementation and additionally having instructions for IDE usage, but what I was sortof expecting was that we could just do the scripting implementations in the book and just make a few notes like "hey reader, you'll likely want to manage your project differently than these examples" but still have code that we can actually run and our readers can aswell to test the logic at least

**Comment by riverKanies** [comment]
I wasn't necessarily planning to worry about "jump to def" for languages other than rust. that was mainly so I can understand and navigate the BDK core (rust) code

**Review by thunderbiscuit — APPROVED** [review]
ACK 413c4cfe5d0c9fa6237d6794b8a92c68063a6f07.

**Pull request merged**
