### PR TITLE
add venv info to readme

### PR DESCRIPTION
**Pull request by riverKanies**
I think it's good to mention that python should generally be used in a virtual environment

### CODE REVIEW

**Review by thunderbiscuit — APPROVED** [review]
ACK 343163d557a18e296cfe3be75739805e7781f116. Thanks!

**Comment by thunderbiscuit** [comment]
Ok actually there are 2 little snags: commit message, and a quick rebase.

### Rebase
Your changes are not made directly on the latest commit on master (I happened to merge something this morning after like 2 months sorry man! lol), so that means I create an extra "merge" commit when merging. This pollutes the commit history and I very much dislike it, and generally don't allow it on repos I maintain. Here you can do a rebase on master and I'll be able to do a clean merge (or I can do it for you if you prefer I don't mind).

### Commit message
I forgot to tell you, but we're using the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format for commit messages: in this case you message is missing a tag, which would be `docs`. You message should be: `docs: add venv info to readme`

I've been trying think of the best tags to use for this repo because in reality they're all "docs" haha, but I think this convention will work fairly well:
- `docs` for things related to the docs about the repo (readme, etc.)
- `book` for things that add/remove/clean up the content of the book
- `companion` for commits that impact the companion codebase

I have not enforced those super strictly in the past but today is the day I start!

**Review by thunderbiscuit — CHANGES_REQUESTED** [review]
Just the 2 little things mentioned above and this is ready to go.

**Comment by riverKanies** [comment]
ok gotcha. I also prefer rebasing in general. although I guess that would mean I need to redo all my PRs every time something gets merged... hmmm I actually don't remember exactly how this was managed on teams I've worked with in the past. I guess the person actually merging did a significant amount of the rebasing...?

with regards to tags: in that case the other pr i submitted should probably have a 'code' and/or 'config' tag

**Review by thunderbiscuit — APPROVED** [review]
ACK c7161469c519012a0249cecc74403d03c4c2b38b

**Pull request merged**
