### PR TITLE
Feature/code breakdown

### PR DESCRIPTION
**Pull request by riverKanies**
This PR builds off of my code snippets PR.

I wanted to go ahead and make an example of what might be an appropriate level of comments on the code. With this update I've added a very trimmed down version of the context pages I made in a previous draft PR. I think this may be closer to the appropriate amount of context to include in the book (keeping in mind that the starter example will have more context than subsequent examples).

### CODE REVIEW

**Comment by riverKanies** [comment]
looks like the team is on board with this direction, so I closed the old pr https://github.com/bitcoindevkit/book-of-bdk/pull/63 and converted this to not be a draft. I'll rebase and may make some minor updates (like removing the print function)

**Comment by riverKanies** [comment]
updated this to use pubkey descriptors and removed the print function.

 I was thinking about removing the full code snippet but I think it's ok to have it in just the first example. other examples we can skip the project creation and build/run and all that and just focus on snippets of interest

**Comment by thunderbiscuit** [comment]
In its current form the page doesn't create any transaction, so I do think using a public key makes sense.

Note that I think the first page should be fully complete example that touches on all parts of the library with very light explanations, to then be expanded upon in further sections and pages; in this sense I do think that this first page merits both an example of building a transaction and persisting the data to disk, hence eventually using private keys.

**Review by thunderbiscuit — COMMENTED** [review]
ACK 4b9bde851794290b2220f1da649b4e8f7cc7180c.

**Pull request merged**
