### PR TITLE
feat: add Core RPC regtest example

### LINKED ISSUE #17: Core RPC example (regtest)
Do we want to bring this back?

https://bitcoindevkit.org/blog/bitcoin-core-rpc-demo/

### PR DESCRIPTION
**Pull request by ValuedMammal**
Adds BDK wallet example using bitcoincore-rpc on regtest. 

may close #17

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Good stuff though. I'll take a look on Monday and try to comment/review. We might be able to fix the one that's already in there and add to it, or I don't mind having more complex examples alongside simple ones. One thing going on in this example I think is that you're using the bitcoin core wallet more extensively, so that I think could be interesting to have because it's a good example for the rpc crate. Anyway I'll take a look next week!

**Comment by ValuedMammal** [comment]
right, probably don't need two of the same. I still had fun working on it, and the site looks beautiful.

**Comment by storopoli** [comment]
@thunderbiscuit need help reviewing this? Just let me know.

**Comment by ValuedMammal** [comment]
Sorry for the confusion, I don't think we plan to retouch this one considering the existing wallet rpc example. I can move to draft or archive it elsewhere. Still happy to hear any feedback though @storopoli

**Pull request closed without merging**
